/* Generated by Frama-C */
extern int printf(char const * __restrict __format , ...);

void show_2d_array(int (*array)[10], int rows)
{
  int i;
  int j;
  i = 0;
  while (i < rows) {
    j = 0;
    while (j < 10) {
      /*@ assert rte: index_bound: 0 ≤ j; */
      /*@ assert rte: index_bound: j < 10; */
      /*@ assert rte: mem_access: \valid_read(&(*(array+i))[j]); */
      printf("array[%d][%d] = %d\n",i,j,(*(array + i))[j]);
      /*@ assert rte: signed_overflow: j+1 ≤ 2147483647; */
      j ++;
    }
    /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
    i ++;
  }
  return;
}

int main(void)
{
  int __retres;
  int a[1][10];
  int b[2][10];
  int c[3][10];
  a[0][0] = 1;
  a[0][1] = 2;
  a[0][2] = 3;
  a[0][3] = 4;
  a[0][4] = 5;
  a[0][5] = 6;
  a[0][6] = 7;
  a[0][7] = 8;
  a[0][8] = 9;
  a[0][9] = 10;
  b[0][0] = 1;
  b[0][1] = 2;
  b[0][2] = 3;
  b[0][3] = 4;
  b[0][4] = 5;
  b[0][5] = 6;
  b[0][6] = 7;
  b[0][7] = 8;
  b[0][8] = 9;
  b[0][9] = 10;
  b[1][0] = 11;
  b[1][1] = 12;
  b[1][2] = 13;
  b[1][3] = 14;
  b[1][4] = 15;
  b[1][5] = 16;
  b[1][6] = 17;
  b[1][7] = 18;
  b[1][8] = 19;
  b[1][9] = 20;
  c[0][0] = 1;
  c[0][1] = 2;
  c[0][2] = 3;
  c[0][3] = 4;
  c[0][4] = 5;
  c[0][5] = 6;
  c[0][6] = 7;
  c[0][7] = 8;
  c[0][8] = 9;
  c[0][9] = 10;
  c[1][0] = 11;
  c[1][1] = 12;
  c[1][2] = 13;
  c[1][3] = 14;
  c[1][4] = 15;
  c[1][5] = 16;
  c[1][6] = 17;
  c[1][7] = 18;
  c[1][8] = 19;
  c[1][9] = 20;
  c[2][0] = 21;
  c[2][1] = 22;
  c[2][2] = 23;
  c[2][3] = 24;
  c[2][4] = 25;
  c[2][5] = 26;
  c[2][6] = 27;
  c[2][7] = 28;
  c[2][8] = 29;
  c[2][9] = 30;
  show_2d_array(a,1);
  show_2d_array(b,2);
  show_2d_array(c,3);
  __retres = 1;
  return __retres;
}


