/* Generated by Frama-C */
typedef unsigned int size_t;
extern int printf(char const * __restrict __format , ...);

extern  __attribute__((__nothrow__)) void *malloc(size_t __size) __attribute__((
__malloc__, __leaf__));

extern  __attribute__((__nothrow__)) char *strcpy(char * __restrict __dest,
                                                  char const * __restrict __src) __attribute__((
__nonnull__(1,2), __leaf__));

int main(void)
{
  int __retres;
  int i;
  char a[6];
  char *p;
  i = 0;
  a[0] = (char)'a';
  a[1] = (char)'b';
  a[2] = (char)'c';
  a[3] = (char)'d';
  a[4] = (char)'e';
  a[5] = (char)'U';
  if (i) {
    p = (char *)malloc((unsigned int)7 * sizeof(char));
    strcpy(p,"ASDFFG");
  }
  else p = a;
  /*@ assert rte: mem_access: \valid_read(p+4); */
  printf("%c\n",*(p + 4));
  __retres = 1;
  return __retres;
}


