/* Generated by Frama-C */
extern int putchar(int __c);

void show_string(char *string)
{
  while (1) {
    char *tmp;
    /*@ assert rte: mem_access: \valid_read(string); */
    if (! *string) break;
    {
      /*undefined sequence*/
      tmp = string;
      string ++;
      ;
    }
    /*@ assert rte: mem_access: \valid_read(tmp); */
    putchar((int)*tmp);
  }
  return;
}

int main(void)
{
  int __retres;
  show_string((char *)"Jamsa\'s 1001 C/C++ Tips");
  __retres = 1;
  return __retres;
}


