/* Generated by Frama-C */
extern int printf(char const * __restrict __format , ...);

extern  __attribute__((__nothrow__)) int strcmp(char const *__s1,
                                                char const *__s2) __attribute__((
__pure__, __nonnull__(1,2), __leaf__));

void bubble_sort(char **array, int size)
{
  char *temp;
  int i;
  int j;
  i = 0;
  while (i < size) {
    j = 0;
    while (j < size) {
      int tmp;
      /*@ assert rte: mem_access: \valid_read(array+i); */
      /*@ assert rte: mem_access: \valid_read(array+j); */
      tmp = strcmp((char const *)*(array + i),(char const *)*(array + j));
      if (tmp < 0) {
        /*@ assert rte: mem_access: \valid_read(array+i); */
        temp = *(array + i);
        /*@ assert rte: mem_access: \valid(array+i); */
        /*@ assert rte: mem_access: \valid_read(array+j); */
        *(array + i) = *(array + j);
        /*@ assert rte: mem_access: \valid(array+j); */
        *(array + j) = temp;
      }
      /*@ assert rte: signed_overflow: j+1 ≤ 2147483647; */
      j ++;
    }
    /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
    i ++;
  }
  /*@ assert rte: mem_access: \valid_read(array+1); */
  /*@ assert rte: mem_access: \valid_read(*(array+1)+2); */
  printf("%c\n",*(*(array + 1) + 2));
  return;
}

int main(void)
{
  int __retres;
  char *values[5];
  int i;
  values[0] = (char *)"AAA";
  values[1] = (char *)"CCCD";
  values[2] = (char *)"BBBDE";
  values[3] = (char *)"EEEDEF";
  values[4] = (char *)"DDDDEFG";
  bubble_sort(values,5);
  i = 0;
  while (i < 5) {
    /*@ assert rte: index_bound: 0 ≤ i; */
    /*@ assert rte: index_bound: i < 5; */
    printf("%s ",values[i]);
    /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
    i ++;
  }
  __retres = 1;
  return __retres;
}


