/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct ( __attribute__((__FC_BUILTIN__)) mpz_t)[1];
typedef unsigned int size_t;
typedef unsigned int ino_t;
typedef unsigned int gid_t;
typedef unsigned int uid_t;
typedef long time_t;
typedef unsigned int blkcnt_t;
typedef unsigned int blksize_t;
typedef unsigned int dev_t;
typedef unsigned int mode_t;
typedef unsigned int nlink_t;
typedef unsigned int off_t;
struct stat {
   dev_t st_dev ;
   ino_t st_ino ;
   mode_t st_mode ;
   nlink_t st_nlink ;
   uid_t st_uid ;
   gid_t st_gid ;
   dev_t st_rdev ;
   off_t st_size ;
   time_t st_atime ;
   time_t st_mtime ;
   time_t st_ctime ;
   blksize_t st_blksize ;
   blkcnt_t st_blocks ;
   char *__fc_real_data ;
   int __fc_real_data_max_size ;
};
struct __fc_FILE {
   unsigned int __fc_stdio_id ;
   unsigned int __fc_maxsz ;
   unsigned int __fc_writepos ;
   unsigned int __fc_readpos ;
   int __fc_is_a_socket ;
   int mode ;
   struct stat *__fc_inode ;
};
typedef struct __fc_FILE FILE;
/*@ requires predicate ≢ 0;
    assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void e_acsl_assert(int predicate,
                                                           char *kind,
                                                           char *fct,
                                                           char *pred_txt,
                                                           int line);

/*@
model __mpz_struct { ℤ n };
*/
int __fc_random_counter __attribute__((__unused__));
unsigned long const __fc_rand_max = (unsigned long)32767;
/*@ ghost extern int __fc_heap_status; */

/*@
axiomatic
  dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ assigns \result \from *((char *)ptr+(0..size-1)); */
extern  __attribute__((__FC_BUILTIN__)) void *__store_block(void *ptr,
                                                            size_t size);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __delete_block(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __initialize(void *ptr,
                                                          size_t size);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __full_init(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __literal_string(void *ptr);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures \result ≡ 1 ⇒ \valid((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __valid(void *ptr, size_t size);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \valid_read((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __valid_read(void *ptr,
                                                         size_t size);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \initialized((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __initialized(void *ptr,
                                                          size_t size);

/*@ assigns __e_acsl_internal_heap;
    assigns __e_acsl_internal_heap \from __e_acsl_internal_heap;
 */
extern  __attribute__((__FC_BUILTIN__)) void __e_acsl_memory_clean(void);

extern size_t __memory_size;

/*@
predicate diffSize{L1, L2}(ℤ i) =
  \at(__memory_size,L1)-\at(__memory_size,L2) ≡ i;
 */
extern FILE *__fc_stdout;

/*@ assigns *__fc_stdout;
    assigns *__fc_stdout \from *(format+(..)); */
extern int printf(char const *format , ...);

int main(void)
{
  char *__e_acsl_literal_string_2;
  char *__e_acsl_literal_string;
  int __retres;
  int a;
  int *b;
  int **c;
  __store_block((void *)(& c),4U);
  __store_block((void *)(& b),4U);
  __store_block((void *)(& a),4U);
  __full_init((void *)(& a));
  a = 5;
  __full_init((void *)(& b));
  b = & a;
  __full_init((void *)(& c));
  c = & b;
  /*@ assert rte: mem_access: \valid_read(c); */
  /*@ assert rte: mem_access: \valid_read(*c); */
  {
    int __e_acsl_initialized;
    int __e_acsl_and_2;
    int __e_acsl_initialized_3;
    int __e_acsl_and_3;
    __e_acsl_initialized = __initialized((void *)c,sizeof(int *));
    if (__e_acsl_initialized) {
      int __e_acsl_initialized_2;
      int __e_acsl_and;
      int __e_acsl_valid_read_2;
      __e_acsl_initialized_2 = __initialized((void *)(& c),sizeof(int **));
      if (__e_acsl_initialized_2) {
        int __e_acsl_valid_read;
        __e_acsl_valid_read = __valid_read((void *)c,sizeof(int *));
        __e_acsl_and = __e_acsl_valid_read;
      }
      else __e_acsl_and = 0;
      e_acsl_assert(__e_acsl_and,(char *)"RTE",(char *)"main",
                    (char *)"mem_access: \\valid_read(c)",7);
      __e_acsl_valid_read_2 = __valid_read((void *)*c,sizeof(int));
      __e_acsl_and_2 = __e_acsl_valid_read_2;
    }
    else __e_acsl_and_2 = 0;
    e_acsl_assert(__e_acsl_and_2,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(*c)",7);
    __e_acsl_initialized_3 = __initialized((void *)(& c),sizeof(int **));
    if (__e_acsl_initialized_3) {
      int __e_acsl_valid_read_3;
      __e_acsl_valid_read_3 = __valid_read((void *)c,sizeof(int *));
      __e_acsl_and_3 = __e_acsl_valid_read_3;
    }
    else __e_acsl_and_3 = 0;
    e_acsl_assert(__e_acsl_and_3,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(c)",7);
    __e_acsl_literal_string = "%d\n";
    __store_block((void *)__e_acsl_literal_string,sizeof("%d\n"));
    __full_init((void *)__e_acsl_literal_string);
    __literal_string((void *)__e_acsl_literal_string);
    printf(__e_acsl_literal_string,*(*c));
  }
  /*@ assert rte: mem_access: \valid(*c); */
  /*@ assert rte: mem_access: \valid_read(c); */
  {
    int __e_acsl_initialized_4;
    int __e_acsl_and_4;
    int __e_acsl_initialized_5;
    int __e_acsl_and_6;
    __e_acsl_initialized_4 = __initialized((void *)(& c),sizeof(int **));
    if (__e_acsl_initialized_4) {
      int __e_acsl_valid_read_4;
      __e_acsl_valid_read_4 = __valid_read((void *)c,sizeof(int *));
      __e_acsl_and_4 = __e_acsl_valid_read_4;
    }
    else __e_acsl_and_4 = 0;
    e_acsl_assert(__e_acsl_and_4,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(c)",8);
    __e_acsl_initialized_5 = __initialized((void *)c,sizeof(int *));
    if (__e_acsl_initialized_5) {
      int __e_acsl_initialized_6;
      int __e_acsl_and_5;
      int __e_acsl_valid;
      __e_acsl_initialized_6 = __initialized((void *)(& c),sizeof(int **));
      if (__e_acsl_initialized_6) {
        int __e_acsl_valid_read_5;
        __e_acsl_valid_read_5 = __valid_read((void *)c,sizeof(int *));
        __e_acsl_and_5 = __e_acsl_valid_read_5;
      }
      else __e_acsl_and_5 = 0;
      e_acsl_assert(__e_acsl_and_5,(char *)"RTE",(char *)"main",
                    (char *)"mem_access: \\valid_read(c)",8);
      __e_acsl_valid = __valid((void *)*c,sizeof(int));
      __e_acsl_and_6 = __e_acsl_valid;
    }
    else __e_acsl_and_6 = 0;
    e_acsl_assert(__e_acsl_and_6,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid(*c)",8);
    __initialize((void *)*c,sizeof(int));
    *(*c) = 10;
  }
  /*@ assert rte: mem_access: \valid_read(c); */
  /*@ assert rte: mem_access: \valid_read(*c); */
  {
    int __e_acsl_initialized_7;
    int __e_acsl_and_8;
    int __e_acsl_initialized_9;
    int __e_acsl_and_9;
    __e_acsl_initialized_7 = __initialized((void *)c,sizeof(int *));
    if (__e_acsl_initialized_7) {
      int __e_acsl_initialized_8;
      int __e_acsl_and_7;
      int __e_acsl_valid_read_7;
      __e_acsl_initialized_8 = __initialized((void *)(& c),sizeof(int **));
      if (__e_acsl_initialized_8) {
        int __e_acsl_valid_read_6;
        __e_acsl_valid_read_6 = __valid_read((void *)c,sizeof(int *));
        __e_acsl_and_7 = __e_acsl_valid_read_6;
      }
      else __e_acsl_and_7 = 0;
      e_acsl_assert(__e_acsl_and_7,(char *)"RTE",(char *)"main",
                    (char *)"mem_access: \\valid_read(c)",9);
      __e_acsl_valid_read_7 = __valid_read((void *)*c,sizeof(int));
      __e_acsl_and_8 = __e_acsl_valid_read_7;
    }
    else __e_acsl_and_8 = 0;
    e_acsl_assert(__e_acsl_and_8,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(*c)",9);
    __e_acsl_initialized_9 = __initialized((void *)(& c),sizeof(int **));
    if (__e_acsl_initialized_9) {
      int __e_acsl_valid_read_8;
      __e_acsl_valid_read_8 = __valid_read((void *)c,sizeof(int *));
      __e_acsl_and_9 = __e_acsl_valid_read_8;
    }
    else __e_acsl_and_9 = 0;
    e_acsl_assert(__e_acsl_and_9,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(c)",9);
    __e_acsl_literal_string_2 = "a=**c=%d\n";
    __store_block((void *)__e_acsl_literal_string_2,sizeof("a=**c=%d\n"));
    __full_init((void *)__e_acsl_literal_string_2);
    __literal_string((void *)__e_acsl_literal_string_2);
    printf(__e_acsl_literal_string_2,*(*c));
  }
  __retres = 1;
  __delete_block((void *)(& c));
  __delete_block((void *)(& b));
  __delete_block((void *)(& a));
  __e_acsl_memory_clean();
  return __retres;
}


