/* Generated by Frama-C */
extern int printf(char const * __restrict __format , ...);

int a[3][3] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
int *b[3] = {a[0], a[1], a[2]};
int **p = b;
int main(void)
{
  int __retres;
  int i;
  int j;
  i = 0;
  while (i < 3) {
    j = 0;
    while (j < 3) {
      /*@ assert rte: index_bound: 0 ≤ i; */
      /*@ assert rte: index_bound: i < 3; */
      /*@ assert rte: mem_access: \valid_read(b[i]+j); */
      /*@ assert rte: mem_access: \valid_read(p+i); */
      /*@ assert rte: mem_access: \valid_read(*(p+i)+j); */
      /*@ assert rte: index_bound: 0 ≤ i; */
      /*@ assert rte: index_bound: i < 3; */
      /*@ assert rte: index_bound: 0 ≤ j; */
      /*@ assert rte: index_bound: j < 3; */
      printf("%d,%d,%d\n",*(b[i] + j),*(*(p + i) + j),a[i][j]);
      /*@ assert rte: signed_overflow: j+1 ≤ 2147483647; */
      j ++;
    }
    /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
    i ++;
  }
  __retres = 1;
  return __retres;
}


