/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct ( __attribute__((__FC_BUILTIN__)) mpz_t)[1];
typedef unsigned int size_t;
/*@ requires predicate ≢ 0;
    assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void e_acsl_assert(int predicate,
                                                           char *kind,
                                                           char *fct,
                                                           char *pred_txt,
                                                           int line);

/*@
model __mpz_struct { ℤ n };
*/
int __fc_random_counter __attribute__((__unused__));
unsigned long const __fc_rand_max = (unsigned long)32767;
/*@ ghost extern int __fc_heap_status; */

/*@
axiomatic
  dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ assigns \result \from *((char *)ptr+(0..size-1)); */
extern  __attribute__((__FC_BUILTIN__)) void *__store_block(void *ptr,
                                                            size_t size);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __delete_block(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __full_init(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __literal_string(void *ptr);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \valid_read((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __valid_read(void *ptr,
                                                         size_t size);

/*@ assigns __e_acsl_internal_heap;
    assigns __e_acsl_internal_heap \from __e_acsl_internal_heap;
 */
extern  __attribute__((__FC_BUILTIN__)) void __e_acsl_memory_clean(void);

extern size_t __memory_size;

/*@
predicate diffSize{L1, L2}(ℤ i) =
  \at(__memory_size,L1)-\at(__memory_size,L2) ≡ i;
 */
/*@ assigns \at(\result,Post) \from *__format; */
extern int printf(char const * __restrict __format , ...);

int a[3][3] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
int *b[3] = {a[0], a[1], a[2]};
int **p = b;
void __e_acsl_memory_init(void)
{
  __store_block((void *)(& p),4U);
  __store_block((void *)(b),12U);
  __store_block((void *)(a),36U);
  return;
}

int main(void)
{
  char *__e_acsl_literal_string;
  int __retres;
  int i;
  int j;
  __e_acsl_memory_init();
  i = 0;
  while (i < 3) {
    j = 0;
    while (j < 3) {
      /*@ assert rte: index_bound: 0 ≤ i; */
      e_acsl_assert(0 <= i,(char *)"Assertion",(char *)"main",
                    (char *)"rte: index_bound: 0 <= i",16);
      /*@ assert rte: index_bound: i < 3; */
      e_acsl_assert(i < 3,(char *)"Assertion",(char *)"main",
                    (char *)"rte: index_bound: i < 3",17);
      /*@ assert rte: mem_access: \valid_read(b[i]+j); */
      {
        int __e_acsl_valid_read;
        e_acsl_assert(i < 3,(char *)"RTE",(char *)"main",
                      (char *)"index_bound: i < 3",18);
        e_acsl_assert(0 <= i,(char *)"RTE",(char *)"main",
                      (char *)"index_bound: 0 <= i",18);
        __e_acsl_valid_read = __valid_read((void *)(b[i] + j),sizeof(int));
        e_acsl_assert(__e_acsl_valid_read,(char *)"Assertion",(char *)"main",
                      (char *)"rte: mem_access: \\valid_read(b[i]+j)",18);
      }
      /*@ assert rte: mem_access: \valid_read(p+i); */
      {
        int __e_acsl_valid_read_2;
        __e_acsl_valid_read_2 = __valid_read((void *)(p + i),sizeof(int *));
        e_acsl_assert(__e_acsl_valid_read_2,(char *)"Assertion",
                      (char *)"main",
                      (char *)"rte: mem_access: \\valid_read(p+i)",19);
      }
      /*@ assert rte: mem_access: \valid_read(*(p+i)+j); */
      {
        int __e_acsl_valid_read_3;
        int __e_acsl_valid_read_4;
        __e_acsl_valid_read_3 = __valid_read((void *)(p + i),sizeof(int *));
        e_acsl_assert(__e_acsl_valid_read_3,(char *)"RTE",(char *)"main",
                      (char *)"mem_access: \\valid_read(p+i)",20);
        __e_acsl_valid_read_4 = __valid_read((void *)(*(p + i) + j),
                                             sizeof(int));
        e_acsl_assert(__e_acsl_valid_read_4,(char *)"Assertion",
                      (char *)"main",
                      (char *)"rte: mem_access: \\valid_read(*(p+i)+j)",20);
      }
      /*@ assert rte: index_bound: 0 ≤ i; */
      e_acsl_assert(0 <= i,(char *)"Assertion",(char *)"main",
                    (char *)"rte: index_bound: 0 <= i",21);
      /*@ assert rte: index_bound: i < 3; */
      e_acsl_assert(i < 3,(char *)"Assertion",(char *)"main",
                    (char *)"rte: index_bound: i < 3",22);
      /*@ assert rte: index_bound: 0 ≤ j; */
      e_acsl_assert(0 <= j,(char *)"Assertion",(char *)"main",
                    (char *)"rte: index_bound: 0 <= j",23);
      /*@ assert rte: index_bound: j < 3; */
      e_acsl_assert(j < 3,(char *)"Assertion",(char *)"main",
                    (char *)"rte: index_bound: j < 3",24);
      __e_acsl_literal_string = "%d,%d,%d\n";
      __store_block((void *)__e_acsl_literal_string,sizeof("%d,%d,%d\n"));
      __full_init((void *)__e_acsl_literal_string);
      __literal_string((void *)__e_acsl_literal_string);
      printf(__e_acsl_literal_string,*(b[i] + j),*(*(p + i) + j),a[i][j]);
      /*@ assert rte: signed_overflow: j+1 ≤ 2147483647; */
      e_acsl_assert((long long)j + (long long)1 <= (long long)2147483647,
                    (char *)"Assertion",(char *)"main",
                    (char *)"rte: signed_overflow: j+1 <= 2147483647",26);
      j ++;
    }
    /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
    e_acsl_assert((long long)i + (long long)1 <= (long long)2147483647,
                  (char *)"Assertion",(char *)"main",
                  (char *)"rte: signed_overflow: i+1 <= 2147483647",29);
    i ++;
  }
  __retres = 1;
  __delete_block((void *)(& p));
  __delete_block((void *)(b));
  __delete_block((void *)(a));
  __e_acsl_memory_clean();
  return __retres;
}


