/* Generated by Frama-C */
extern int printf(char const * __restrict __format , ...);

int main(void)
{
  int __retres;
  char *workdays[6];
  char **work_day;
  workdays[0] = (char *)"Monday";
  workdays[1] = (char *)"Tuesday";
  workdays[2] = (char *)"Wednesday";
  workdays[3] = (char *)"Thursday";
  workdays[4] = (char *)"Friday";
  workdays[5] = (char *)"";
  work_day = workdays;
  while (1) {
    char **tmp;
    /*@ assert rte: mem_access: \valid_read(work_day); */
    if (! *work_day) break;
    {
      /*undefined sequence*/
      tmp = work_day;
      work_day ++;
      ;
    }
    /*@ assert rte: mem_access: \valid_read(tmp); */
    printf("%s\n",*tmp);
  }
  __retres = 1;
  return __retres;
}


