/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct ( __attribute__((__FC_BUILTIN__)) mpz_t)[1];
typedef unsigned int size_t;
/*@ requires predicate ≢ 0;
    assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void e_acsl_assert(int predicate,
                                                           char *kind,
                                                           char *fct,
                                                           char *pred_txt,
                                                           int line);

/*@
model __mpz_struct { ℤ n };
*/
int __fc_random_counter __attribute__((__unused__));
unsigned long const __fc_rand_max = (unsigned long)32767;
/*@ ghost extern int __fc_heap_status; */

/*@
axiomatic
  dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ assigns \result \from *((char *)ptr+(0..size-1)); */
extern  __attribute__((__FC_BUILTIN__)) void *__store_block(void *ptr,
                                                            size_t size);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __delete_block(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __initialize(void *ptr,
                                                          size_t size);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __full_init(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __literal_string(void *ptr);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \valid_read((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __valid_read(void *ptr,
                                                         size_t size);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \initialized((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __initialized(void *ptr,
                                                          size_t size);

/*@ assigns __e_acsl_internal_heap;
    assigns __e_acsl_internal_heap \from __e_acsl_internal_heap;
 */
extern  __attribute__((__FC_BUILTIN__)) void __e_acsl_memory_clean(void);

extern size_t __memory_size;

/*@
predicate diffSize{L1, L2}(ℤ i) =
  \at(__memory_size,L1)-\at(__memory_size,L2) ≡ i;
 */
/*@ assigns \at(\result,Post) \from *__format; */
extern int printf(char const * __restrict __format , ...);

int main(void)
{
  char *__e_acsl_literal_string_7;
  char *__e_acsl_literal_string_6;
  char *__e_acsl_literal_string_5;
  char *__e_acsl_literal_string_4;
  char *__e_acsl_literal_string_3;
  char *__e_acsl_literal_string_2;
  char *__e_acsl_literal_string;
  int __retres;
  char *workdays[6];
  char **work_day;
  __store_block((void *)(& work_day),4U);
  __store_block((void *)(workdays),24U);
  __e_acsl_literal_string = "Monday";
  __store_block((void *)__e_acsl_literal_string,sizeof("Monday"));
  __full_init((void *)__e_acsl_literal_string);
  __literal_string((void *)__e_acsl_literal_string);
  __initialize((void *)(workdays),sizeof(char *));
  workdays[0] = (char *)__e_acsl_literal_string;
  __e_acsl_literal_string_2 = "Tuesday";
  __store_block((void *)__e_acsl_literal_string_2,sizeof("Tuesday"));
  __full_init((void *)__e_acsl_literal_string_2);
  __literal_string((void *)__e_acsl_literal_string_2);
  __initialize((void *)(& workdays[1]),sizeof(char *));
  workdays[1] = (char *)__e_acsl_literal_string_2;
  __e_acsl_literal_string_3 = "Wednesday";
  __store_block((void *)__e_acsl_literal_string_3,sizeof("Wednesday"));
  __full_init((void *)__e_acsl_literal_string_3);
  __literal_string((void *)__e_acsl_literal_string_3);
  __initialize((void *)(& workdays[2]),sizeof(char *));
  workdays[2] = (char *)__e_acsl_literal_string_3;
  __e_acsl_literal_string_4 = "Thursday";
  __store_block((void *)__e_acsl_literal_string_4,sizeof("Thursday"));
  __full_init((void *)__e_acsl_literal_string_4);
  __literal_string((void *)__e_acsl_literal_string_4);
  __initialize((void *)(& workdays[3]),sizeof(char *));
  workdays[3] = (char *)__e_acsl_literal_string_4;
  __e_acsl_literal_string_5 = "Friday";
  __store_block((void *)__e_acsl_literal_string_5,sizeof("Friday"));
  __full_init((void *)__e_acsl_literal_string_5);
  __literal_string((void *)__e_acsl_literal_string_5);
  __initialize((void *)(& workdays[4]),sizeof(char *));
  workdays[4] = (char *)__e_acsl_literal_string_5;
  __e_acsl_literal_string_6 = "";
  __store_block((void *)__e_acsl_literal_string_6,sizeof(""));
  __full_init((void *)__e_acsl_literal_string_6);
  __literal_string((void *)__e_acsl_literal_string_6);
  __initialize((void *)(& workdays[5]),sizeof(char *));
  workdays[5] = (char *)__e_acsl_literal_string_6;
  __full_init((void *)(& work_day));
  work_day = workdays;
  while (1) {
    {
      char **tmp;
      __store_block((void *)(& tmp),4U);
      /*@ assert rte: mem_access: \valid_read(work_day); */
      {
        int __e_acsl_initialized;
        int __e_acsl_and;
        __e_acsl_initialized = __initialized((void *)(& work_day),
                                             sizeof(char **));
        if (__e_acsl_initialized) {
          int __e_acsl_valid_read;
          __e_acsl_valid_read = __valid_read((void *)work_day,sizeof(char *));
          __e_acsl_and = __e_acsl_valid_read;
        }
        else __e_acsl_and = 0;
        e_acsl_assert(__e_acsl_and,(char *)"Assertion",(char *)"main",
                      (char *)"rte: mem_access: \\valid_read(work_day)",18);
      }
      if (! *work_day) break;
      __full_init((void *)(& tmp));
      tmp = work_day;
      __full_init((void *)(& work_day));
      work_day ++;
      /*@ assert rte: mem_access: \valid_read(tmp); */
      {
        int __e_acsl_initialized_2;
        int __e_acsl_and_2;
        __e_acsl_initialized_2 = __initialized((void *)(& tmp),
                                               sizeof(char **));
        if (__e_acsl_initialized_2) {
          int __e_acsl_valid_read_2;
          __e_acsl_valid_read_2 = __valid_read((void *)tmp,sizeof(char *));
          __e_acsl_and_2 = __e_acsl_valid_read_2;
        }
        else __e_acsl_and_2 = 0;
        e_acsl_assert(__e_acsl_and_2,(char *)"Assertion",(char *)"main",
                      (char *)"rte: mem_access: \\valid_read(tmp)",26);
      }
      __e_acsl_literal_string_7 = "%s\n";
      __store_block((void *)__e_acsl_literal_string_7,sizeof("%s\n"));
      __full_init((void *)__e_acsl_literal_string_7);
      __literal_string((void *)__e_acsl_literal_string_7);
      printf(__e_acsl_literal_string_7,*tmp);
      __delete_block((void *)(& tmp));
    }
  }
  __retres = 1;
  __delete_block((void *)(& work_day));
  __delete_block((void *)(workdays));
  __e_acsl_memory_clean();
  return __retres;
}


