/* Generated by Frama-C */
typedef unsigned int size_t;
struct data_type {
   int age ;
   char name[20][30] ;
};
typedef struct data_type data;
extern int printf(char const * __restrict __format , ...);

extern  __attribute__((__nothrow__)) void *malloc(size_t __size) __attribute__((
__malloc__, __leaf__));

extern  __attribute__((__nothrow__)) char *strcpy(char * __restrict __dest,
                                                  char const * __restrict __src) __attribute__((
__nonnull__(1,2), __leaf__));

int main(void)
{
  int __retres;
  data *bob1;
  bob1 = (data *)malloc(sizeof(data));
  strcpy(bob1->name[1],"Robert");
  /*@ assert rte: mem_access: \valid_read(&bob1->name[1][2]); */
  printf("%c\n",bob1->name[1][2]);
  __retres = 0;
  return __retres;
}


