/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct ( __attribute__((__FC_BUILTIN__)) mpz_t)[1];
typedef unsigned int size_t;
struct struct1 {
   int len ;
   int interp ;
};
struct struct2 {
   int len ;
   char *string ;
   char string1[10] ;
   int interp ;
};
struct struct3 {
   int len ;
   char array[10] ;
};
/*@ requires predicate ≢ 0;
    assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void e_acsl_assert(int predicate,
                                                           char *kind,
                                                           char *fct,
                                                           char *pred_txt,
                                                           int line);

/*@
model __mpz_struct { ℤ n };
*/
int __fc_random_counter __attribute__((__unused__));
unsigned long const __fc_rand_max = (unsigned long)32767;
/*@ ghost extern int __fc_heap_status; */

/*@
axiomatic
  dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ assigns \result \from *((char *)ptr+(0..size-1)); */
extern  __attribute__((__FC_BUILTIN__)) void *__store_block(void *ptr,
                                                            size_t size);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __delete_block(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __full_init(void *ptr);

/*@ assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void __literal_string(void *ptr);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \valid_read((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __valid_read(void *ptr,
                                                         size_t size);

/*@ ensures \result ≡ 0 ∨ \result ≡ 1;
    ensures
      \result ≡ 1 ⇒ \initialized((char *)\old(ptr)+(0..\old(size)-1));
    assigns \result \from *((char *)ptr+(0..size-1));
 */
extern  __attribute__((__FC_BUILTIN__)) int __initialized(void *ptr,
                                                          size_t size);

/*@ assigns __e_acsl_internal_heap;
    assigns __e_acsl_internal_heap \from __e_acsl_internal_heap;
 */
extern  __attribute__((__FC_BUILTIN__)) void __e_acsl_memory_clean(void);

extern size_t __memory_size;

/*@
predicate diffSize{L1, L2}(ℤ i) =
  \at(__memory_size,L1)-\at(__memory_size,L2) ≡ i;
 */
/*@ assigns \at(\result,Post) \from *__format; */
extern int printf(char const * __restrict __format , ...);

struct struct1 s[6] = {{6, 1}, {4, 0}, {5, 0}, {5, 0}, {6, 0}, {2, 0}};
struct struct2 ss[8];
struct struct3 sss[2] = {{1,
                          {(char)'a', (char)'s', (char)'d', (char)'f',
                           (char)'\000'}},
                         {2,
                          {(char)'d', (char)'f', (char)'d', (char)'s',
                           (char)'\000'}}};
void __e_acsl_memory_init(void)
{
  char *__e_acsl_literal_string;
  __store_block((void *)(ss),192U);
  __e_acsl_literal_string = "undefine";
  __store_block((void *)__e_acsl_literal_string,sizeof("undefine"));
  __full_init((void *)__e_acsl_literal_string);
  __literal_string((void *)__e_acsl_literal_string);
  ss = (char *)__e_acsl_literal_string;
  return;
}

int main(void)
{
  char *__e_acsl_literal_string_4;
  char *__e_acsl_literal_string_3;
  char *__e_acsl_literal_string_2;
  char *__e_acsl_literal_string;
  int __retres;
  struct struct2 *p;
  char *q;
  char *n;
  char *m;
  char **l;
  __e_acsl_memory_init();
  __store_block((void *)(& l),4U);
  __store_block((void *)(& q),4U);
  __store_block((void *)(& p),4U);
  __full_init((void *)(& p));
  p = ss;
  /*@ assert rte: mem_access: \valid_read(&(p+2)->string); */
  {
    int __e_acsl_valid_read;
    __e_acsl_valid_read = __valid_read((void *)(& (p + 2)->string),
                                       sizeof(char *));
    e_acsl_assert(__e_acsl_valid_read,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(&(p+2)->string)",67);
  }
  __full_init((void *)(& q));
  q = (p + 2)->string + 3;
  /*@ assert rte: mem_access: \valid_read(&(p+2)->string); */
  {
    int __e_acsl_valid_read_2;
    __e_acsl_valid_read_2 = __valid_read((void *)(& (p + 2)->string),
                                         sizeof(char *));
    e_acsl_assert(__e_acsl_valid_read_2,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(&(p+2)->string)",69);
  }
  n = (p + 2)->string;
  m = (p + 3)->string1;
  __full_init((void *)(& l));
  l = & q;
  __e_acsl_literal_string = "%s\n";
  __store_block((void *)__e_acsl_literal_string,sizeof("%s\n"));
  __full_init((void *)__e_acsl_literal_string);
  __literal_string((void *)__e_acsl_literal_string);
  printf(__e_acsl_literal_string,q);
  __e_acsl_literal_string_2 = "%s\n";
  __store_block((void *)__e_acsl_literal_string_2,sizeof("%s\n"));
  __full_init((void *)__e_acsl_literal_string_2);
  __literal_string((void *)__e_acsl_literal_string_2);
  printf(__e_acsl_literal_string_2,n);
  __e_acsl_literal_string_3 = "%s\n";
  __store_block((void *)__e_acsl_literal_string_3,sizeof("%s\n"));
  __full_init((void *)__e_acsl_literal_string_3);
  __literal_string((void *)__e_acsl_literal_string_3);
  printf(__e_acsl_literal_string_3,m);
  /*@ assert rte: mem_access: \valid_read(l); */
  {
    int __e_acsl_initialized;
    int __e_acsl_and;
    __e_acsl_initialized = __initialized((void *)(& l),sizeof(char **));
    if (__e_acsl_initialized) {
      int __e_acsl_valid_read_3;
      __e_acsl_valid_read_3 = __valid_read((void *)l,sizeof(char *));
      __e_acsl_and = __e_acsl_valid_read_3;
    }
    else __e_acsl_and = 0;
    e_acsl_assert(__e_acsl_and,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(l)",76);
  }
  /*@ assert rte: mem_access: \valid_read(*l); */
  {
    int __e_acsl_initialized_2;
    int __e_acsl_and_3;
    __e_acsl_initialized_2 = __initialized((void *)l,sizeof(char *));
    if (__e_acsl_initialized_2) {
      int __e_acsl_initialized_3;
      int __e_acsl_and_2;
      int __e_acsl_valid_read_5;
      __e_acsl_initialized_3 = __initialized((void *)(& l),sizeof(char **));
      if (__e_acsl_initialized_3) {
        int __e_acsl_valid_read_4;
        __e_acsl_valid_read_4 = __valid_read((void *)l,sizeof(char *));
        __e_acsl_and_2 = __e_acsl_valid_read_4;
      }
      else __e_acsl_and_2 = 0;
      e_acsl_assert(__e_acsl_and_2,(char *)"RTE",(char *)"main",
                    (char *)"mem_access: \\valid_read(l)",77);
      __e_acsl_valid_read_5 = __valid_read((void *)*l,sizeof(char));
      __e_acsl_and_3 = __e_acsl_valid_read_5;
    }
    else __e_acsl_and_3 = 0;
    e_acsl_assert(__e_acsl_and_3,(char *)"Assertion",(char *)"main",
                  (char *)"rte: mem_access: \\valid_read(*l)",77);
  }
  __e_acsl_literal_string_4 = "%c\n";
  __store_block((void *)__e_acsl_literal_string_4,sizeof("%c\n"));
  __full_init((void *)__e_acsl_literal_string_4);
  __literal_string((void *)__e_acsl_literal_string_4);
  printf(__e_acsl_literal_string_4,*(*l));
  __retres = 0;
  __delete_block((void *)(ss));
  __delete_block((void *)(& l));
  __delete_block((void *)(& q));
  __delete_block((void *)(& p));
  __e_acsl_memory_clean();
  return __retres;
}


