/* Generated by Frama-C */
struct struct1 {
   int len ;
   int interp ;
};
struct struct2 {
   int len ;
   char *string ;
   char string1[10] ;
   int interp ;
};
struct struct3 {
   int len ;
   char array[10] ;
};
extern int printf(char const * __restrict __format , ...);

struct struct1 s[6] = {{6, 1}, {4, 0}, {5, 0}, {5, 0}, {6, 0}, {2, 0}};
struct struct2 ss[8] =   
                         {{6, (char *)"define",
                           {(char)'a', (char)'s', (char)'d', (char)'f',
                            (char)'s', (char)'\000'},
                           1},
                          {4, (char *)"else",
                           {(char)'s', (char)'d', (char)'f', (char)'s',
                            (char)'f', (char)'\000'},
                           0},
                          {5, (char *)"endif",
                           {(char)'s', (char)'d', (char)'f', (char)'w',
                            (char)'e', (char)'q', (char)'\000'},
                           0},
                          {5, (char *)"ifdef",
                           {(char)'w', (char)'e', (char)'r', (char)'e',
                            (char)'w', (char)'\000'},
                           0},
                          {6, (char *)"ifndef",
                           {(char)'e', (char)'w', (char)'r', (char)'e',
                            (char)'w', (char)'q', (char)'\000'},
                           0},
                          {2, (char *)"if",
                           {(char)'q', (char)'w', (char)'e', (char)'w',
                            (char)'q', (char)'\000'},
                           0},
                          {7, (char *)"include",
                           {(char)'r', (char)'t', (char)'y', (char)'r',
                            (char)'t', (char)'u', (char)'\000'},
                           1},
                          {8, (char *)"undefine",
                           {(char)'t', (char)'y', (char)'u', (char)'y',
                            (char)'t', (char)'u', (char)'\000'},
                           1}};
struct struct3 sss[2] = {{1,
                          {(char)'a', (char)'s', (char)'d', (char)'f',
                           (char)'\000'}},
                         {2,
                          {(char)'d', (char)'f', (char)'d', (char)'s',
                           (char)'\000'}}};
int main(void)
{
  int __retres;
  struct struct2 *p;
  char *q;
  char *n;
  char *m;
  char **l;
  p = ss;
  /*@ assert rte: mem_access: \valid_read(&(p+2)->string); */
  q = (p + 2)->string + 3;
  /*@ assert rte: mem_access: \valid_read(&(p+2)->string); */
  n = (p + 2)->string;
  m = (p + 3)->string1;
  l = & q;
  printf("%s\n",q);
  printf("%s\n",n);
  printf("%s\n",m);
  /*@ assert rte: mem_access: \valid_read(l); */
  /*@ assert rte: mem_access: \valid_read(*l); */
  printf("%c\n",*(*l));
  __retres = 0;
  return __retres;
}


