/* Generated by Frama-C */
extern int printf(char const * __restrict __format , ...);

_Bool conver(int *d, int *b)
{
  _Bool __retres;
  int i;
  int c[5];
  i = 0;
  while (i < 5) {
    /*@ assert rte: mem_access: \valid(d+i); */
    /*@ assert rte: mem_access: \valid_read(b+i); */
    *(d + i) = *(b + i);
    /*@ assert rte: index_bound: 0 ≤ i; */
    /*@ assert rte: index_bound: i < 5; */
    /*@ assert rte: mem_access: \valid_read(b+i); */
    c[i] = *(b + i);
    /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
    i ++;
  }
  __retres = (_Bool)1;
  return __retres;
}

static int a[10];
int main(void)
{
  int __retres;
  int i;
  int num[5];
  _Bool tmp;
  num[0] = 1;
  num[1] = 2;
  num[2] = 3;
  num[3] = 4;
  num[4] = 5;
  tmp = conver(a,num);
  if (tmp) {
    i = 0;
    while (i < 5) {
      /*@ assert rte: index_bound: 0 ≤ i; */
      /*@ assert rte: index_bound: i < 10; */
      printf("%d  ",a[i]);
      /*@ assert rte: signed_overflow: i+1 ≤ 2147483647; */
      i ++;
    }
  }
  __retres = 1;
  return __retres;
}


